BASE_EPISODES_PER_CLICK = 0.1
BASE_EPISODES_PER_SEASON = 2
BASE_MAX_SUBSCRIBERS_PER_EPISODE = 1
BASE_MIN_SUBSCRIBERS_PER_EPISODE = 0
BASE_MONEY_PER_VIEW = 0.001
BASE_TICKS_TO_PROCESS_EPISODE = 600
BASE_VIEWS_PER_EPISODE = 10