PREFIXES = [
    'Aussparung',
    'Alphorn',
    'Amoklauf',
    'Antifa',
    'Asteroid',
    'Babitsch',
    'Beer',
    'Brot',
    'Bullshit',
    'Cake',
    'Camlelot',
    'Candy',
    'Chicken Nugget',
    'Chili',
    'Circle',
    'Clonker',
    'Coin',
    'Cookie',
    'Cow',
    'Crystal',
    'Cthulhu',
    'Darkside Park',
    'Darth',
    'Diamond',
    'Die drei XXX',
    'Doomed',
    'Drawing',
    'Erbswurst',
    'Fight Club',
    'Fox',
    'Froppelcopter',
    'Gem',
    'Gold',
    'Hairy Plautzen',
    'Hamburger',
    'Hamster',
    'Icecream',
    'Idle',
    'Just one more Level',
    'Kack in den Traktor',
    'Kauf meinen Scheiss',
    'Knoblauch',
    'Kot',
    'Loot',
    'Meat',
    'Metal',
    'Metaluna',
    'Mineral',
    'Money',
    'Mopsfotzes',
    'Nazi',
    'Oil',
    'Oyster',
    'Panzer',
    'Plankton',
    'Plushkitty',
    'Plutonium',
    'Pogo',
    'Porn',
    'Potato',
    'Prengelschneck',
    'Proton',
    'Rainbow',
    'Rettich',
    'Ringelpietz',
    'Ruby',
    'Rum',
    'Salmon',
    'Schinken',
    'Schmalz',
    'Schnapps',
    'Spider',
    'Trackball',
    'Ukulele',
    'Unicorn',
    'Uranium',
    'Wall of',
    'Weed',
    'Wunderland',
    'Ziegelstein',
    'Zwielicht'
]
NAMES = [
    '- Folge 4: Der Perverse Perser',
    'Adventure',
    'Banker',
    'Baron',
    'broker',
    'Builder',
    'Capitalist',
    'Clicker',
    'Collector',
    'Commander',
    'Das Musical',
    'Death',
    'Die Simulation',
    'Emperor',
    'Extractor',
    'Farmer',
    'From Outer Space',
    'Funtime',
    'Games',
    'General',
    'Grinder',
    'Hero',
    'Hoarder',
    'Hunter',
    'In Der Strassenbahn',
    'Investor',
    'Journey',
    'Joyride',
    'King',
    'Klick till you bleed',
    'Klickerspass',
    'Knight',
    'Knotzen',
    'Kuemmel',
    'Kumpel',
    'Looter',
    'Manager',
    'Miner',
    'Mit Anfassen',
    'Oligarch',
    'Pinball Madness',
    'Pirate',
    'Pit',
    'President',
    'Ranger'
    'Teaser',
]
SUFFIXES = [
    '- Early Access -',
    '- With In-App Purchases -',
    '3D',
    '4.0',
    '5.0 Deutschland Edition',
    'Achja?',
    'Beta',
    'Deluxe',
    'Dem Verfassungsschutz gefaellt das',
    'Es ist alles wahr...',
    'Forever',
    'Forke Edition',
    'Game Of The Year Edition',
    'Genau so klingt Volksmusik fuer Hunde',
    'Gold Edition',
    'Hose zu!',
    'Ich glaube es wird wieder gearbeitet!',
    'In Space',
    'Jetzt mit mehr Gelee',
    'Mit extra Snoopsies',
    'Ultimate',
    'Und wenn man das durch 2 teilt?',
    'Und wenn man das umdreht?',
    'United',
    'Voiced by Daniel Schroeder',
    'VR',
    'Z',
]
