#Copyright 2016 Stefan Winterfeldt
#This file is part of Idle Bensch.
#
#Idle Bensch is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Idle Bensch is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with Idle Bensch.  If not, see <http://www.gnu.org/licenses/>.

PREFIXES = [
    'Alphorn',
    'Amoklauf',
    'Antifa',
    'Asteroid',
    'Aussparung',
    'Babitsch',
    'Beer',
    'Brot',
    'Bullshit',
    'Cake',
    'Camlelot',
    'Candy',
    'Chicken Nugget',
    'Chili',
    'Circle',
    'Clonker',
    'Coin',
    'Cookie',
    'Cow',
    'Crystal',
    'Cthulhu',
    'Darkside Park',
    'Darth',
    'Diamond',
    'Doomed',
    'Drawing',
    'Erbswurst',
    'Fight Club',
    'Fox',
    'Froppelcopter',
    'Gem',
    'Gold',
    'Hairy Plautzen',
    'Hamburger',
    'Hamster',
    'Icecream',
    'Idle',
    'Just one more Level',
    'Kack in den Traktor',
    'Knoblauch',
    'Knotzen',
    'Kot',
    'Kuemmel',
    'Loot',
    'Meat',
    'Metal',
    'Metaluna',
    'Mineral',
    'Money',
    'Mopsfotzes',
    'Nazi',
    'Oil',
    'Oyster',
    'Panzer',
    'Plankton',
    'Plushkitty',
    'Plutonium',
    'Pogo',
    'Porn',
    'Potato',
    'Prengelschneck',
    'Proton',
    'Rainbow',
    'Rettich',
    'Ringelpietz',
    'Ruby',
    'Rum',
    'Salmon',
    'Schinken',
    'Schmalz',
    'Schnapps',
    'Spider',
    'Trackball',
    'Ukulele',
    'Unicorn',
    'Uranium',
    'Weed',
    'Wunderland',
    'Ziegelstein',
    'Zwielicht'
]
NAMES = [
    'Adventure',
    'Banker',
    'Baron',
    'Broker',
    'Builder',
    'Capitalist',
    'Clicker',
    'Collector',
    'Commander',
    'Death',
    'Emperor',
    'Extractor',
    'Farmer',
    'From Outer Space',
    'Funtime',
    'General',
    'Grinder',
    'Hero',
    'Hoarder',
    'Hunter',
    'In Der Strassenbahn',
    'Investor',
    'Journey',
    'Joyride',
    'King',
    'Klick till you bleed',
    'Klickerspass',
    'Knight',
    'Kumpel',
    'Looter',
    'Manager',
    'Miner',
    'Oligarch',
    'Pinball Madness',
    'Pirate',
    'Pit',
    'President',
    'Ranger',
    'Teaser'
]
SUFFIXES = [
    '- Early Access -',
    '- With In-App Purchases -',
    '3D',
    '4.0',
    '5.0 Deutschland Edition',
    'Achja?',
    'Beta',
    'Das Musical',
    'Deluxe',
    'Dem Verfassungsschutz gefaellt das',
    'Es ist alles wahr...',
    'Forever',
    'Forke Edition',
    'Genau so klingt Volksmusik fuer Hunde',
    'Gold Edition',
    'GotY Edition',
    'Hose zu!',
    'Ich glaube es wird wieder gearbeitet!',
    'In Space',
    'Jetzt mit mehr Gelee',
    'Mit Anfassen',
    'Mit extra Snoopsies',
    'Ultimate',
    'Und wenn man das durch 2 teilt?',
    'Und wenn man das umdreht?',
    'United',
    'Voiced by Daniel Schroeder',
    'VR',
    'Z',
]
