PREFIXES = [
    'Alphorn',
    'Asteroid',
    'Beer',
    'Brot',
    'Cake',
    'Candy',
    'Chicken Nugget',
    'Chili',
    'Coin',
    'Cookie',
    'Cow',
    'Crystal',
    'Diamond',
    'Erbswurst',
    'Fox',
    'Gem',
    'Gold',
    'Hamburger',
    'Hamster',
    'Icecream',
    'Idle',
    'Knoblauch',
    'Kot',
    'Loot',
    'Meat',
    'Metal',
    'Mineral',
    'Money',
    'Oil',
    'Oyster',
    'Plankton',
    'Plutonium',
    'Porn',
    'Potato',
    'Prengelschneck',
    'Proton',
    'Rainbow',
    'Rettich',
    'Ruby',
    'Rum',
    'Salmon',
    'Schinken',
    'Schmalz',
    'Schnapps',
    'Spider',
    'Ukulele',
    'Unicorn',
    'Uranium',
    'Weed',
    'Ziegelstein',
]
NAMES = [
    'Banker',
    'Baron',
    'broker',
    'Builder',
    'Capitalist',
    'Clicker',
    'Collector',
    'Commander',
    'Emperor',
    'Extractor',
    'Farmer',
    'General',
    'Grinder',
    'Hero',
    'Hoarder',
    'Hunter',
    'Investor',
    'Miner',
    'King',
    'Knight',
    'Kumpel',
    'Looter',
    'Oligarch',
    'Pirate',
    'President',
    'Ranger'
]
SUFFIXES = [
    '- Early Access -',
    '- With In-App Purchases -',
    '3D',
    '4.0',
    'Deluxe',
    'Forever',
    'Game Of The Year Edition',
    'Gold Edition',
    'In Space',
    'Ultimate',
    'United',
    'VR',
    'Z'
]
