import globals.gameLogic as GL
import globals.gameState as GS

def deactivateGameLogic ():
    GL.BASE_CLICKS_PER_SECOND = 0.0
    GL.BASE_DONATION_CHANCE_PER_STREAM_PER_SECOND = 0.0
    GL.BASE_PURCHASE_CHANCE_PER_SUBSCRIBER_PER_SECOND = 0.0
    GL.BASE_EPISODES_PER_CLICK = 0.0
    GL.BASE_EPISODES_PER_SEASON = 100.0
    GL.BASE_MAX_DONATION = 0.0
    GL.BASE_MAX_PURCHASE = 0.0
    GL.BASE_MAX_SUBSCRIBERS_PER_EPISODE = 0.0
    GL.BASE_MAX_SUBSCRIBERS_PER_SEASON = 0.0
    GL.BASE_MIN_DONATION = 0.0
    GL.BASE_MIN_PURCHASE = 0.0
    GL.BASE_MIN_SUBSCRIBERS_PER_EPISODE = 0.0
    GL.BASE_MIN_SUBSCRIBERS_PER_SEASON = 0.0
    GL.BASE_MONEY_PER_VIEW = 0.0
    GL.BASE_SUBSCRIBER_VIEWS_PER_EPISODE = 0.0
    GL.BASE_SUBSCRIBERS_PER_STREAM_PER_SECOND = 0.0
    GL.BASE_SECONDS_TO_PROCESS_EPISODE = 10
    GL.BASE_SECONDS_TO_PROCESS_SEASON = 100
    GL.BASE_VIEWS_PER_EPISODE = 0.0

def activateEnding ():
    GS.endingInProgress = True
    deactivateGameLogic ()

def initialize ():
    pass

def update ():
    pass
